language: objective-c
osx_image: xcode10.3
script:
  - xcodebuild -project RHPlaceholder/RHPlaceholder.xcodeproj -target RHPlaceholder -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.4'