# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'RHPlaceholderExample' do

	pod 'RHPlaceholder', :git => 'https://github.com/robertherdzik/RHPlaceholder/tree/pod_addd/RHPlaceholder'
end
